'use client';

import * as React from 'react';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from './ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from './ui/accordion';
import { Badge } from './ui/badge';
import { Button } from './ui/button';
import { Download } from 'lucide-react';
import { exportToCsv } from '@/lib/csv-export';

interface DataTableProps {
  data: any[];
}

export function DataTable({ data }: DataTableProps) {

  const handleExport = () => {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    exportToCsv(data, `neurogen-data-${timestamp}`);
  }

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
            <CardTitle>Generated Medical Records</CardTitle>
            <CardDescription>A list of synthetic medical records generated by the AI.</CardDescription>
        </div>
        <Button variant="outline" size="sm" onClick={handleExport}>
            <Download className="mr-2 h-4 w-4" />
            Download CSV
        </Button>
      </CardHeader>
      <CardContent>
        <div className="rounded-md border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[150px]">Patient ID</TableHead>
                <TableHead>Diagnosis</TableHead>
                <TableHead>Age</TableHead>
                <TableHead>Gender</TableHead>
                <TableHead className="w-[100px]">Details</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {data.map((item, index) => (
                <Accordion key={item?.patientId || index} type="single" collapsible asChild>
                   <AccordionItem value={`item-${index}`} asChild>
                    <>
                        <TableRow>
                            <TableCell className="font-medium">{item?.patientId || 'N/A'}</TableCell>
                            <TableCell>
                                <Badge variant="secondary">{item?.diagnosis || 'N/A'}</Badge>
                            </TableCell>
                            <TableCell>{item?.age || 'N/A'}</TableCell>
                            <TableCell>{item?.gender || 'N/A'}</TableCell>
                            <TableCell>
                                <AccordionTrigger>View</AccordionTrigger>
                            </TableCell>
                        </TableRow>
                        <TableRow>
                            <TableCell colSpan={5} className="p-0">
                                <AccordionContent>
                                    <div className="p-4 bg-muted">
                                        <h4 className="font-semibold mb-2">Enriched Record Details:</h4>
                                        <pre className="bg-background p-4 rounded-md text-xs overflow-x-auto">
                                            {JSON.stringify(item, null, 2)}
                                        </pre>
                                    </div>
                                </AccordionContent>
                            </TableCell>
                        </TableRow>
                    </>
                   </AccordionItem>
                </Accordion>
              ))}
            </TableBody>
          </Table>
        </div>
      </CardContent>
    </Card>
  );
}
